version: '3'
services:
 weblogic:
   image: vulhub/weblogic:12.2.1.3-2018
   container_name: weblogic
   networks: 
    weblogic_net:
      ipv4_address: 172.25.0.2
networks:
  weblogic_net:
    name: weblogic_net
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.25.0.0/16
    driver_opts: 
      com.docker.network.bridge.name: br_weblogic_int
