<?php
return [
    'type'           => 'mysql',
    'hostname'       => 'mysql',
    'database'       => 'cat',
    'username'       => 'root',
    'password'       => 'wNpAFoSndKjA',
    'hostport'       => '',
    'dsn'            => '',
    'params'         => [],
    'charset'        => 'utf8',
    'prefix'         => '',
    'debug'          => true,
    'deploy'         => 0,
    'rw_separate'    => false,
    'master_num'     => 1,
    'slave_no'       => '',
    'fields_strict'  => true,
    'resultset_type' => 'array',
    'auto_timestamp' => false,
    'sql_explain'    => false,
];
